Update deps
RatioPBC/epi-contacts pull request #12
Opened 2021-12-03 01:05 UTC by patmaddox

2021-12-03 01:06 UTC, patmaddox commented
@jc00ke I am a bit skeptical that these updates are good, because while installing deps I saw some undefined function warnings related to crypto, similar as what we ran into the other day. They're in the Paseto library. Is that a part of code that just may not have enough test coverage?

2021-12-05 23:38 UTC, jc00ke commented
https://github.com/RatioPBC/epi-contacts/blob/main/lib/epi_contacts/secure_id.ex
https://github.com/RatioPBC/epi-contacts/blob/main/test/epi_contacts/secure_id_test.exs

It's got test coverage, integration style. We may want to rev the Paseto version at some point from v2 to v4 or whatever the latest is.

2021-12-06 17:16 UTC, patmaddox commented
> It's got test coverage, integration style. We may want to rev the Paseto version at some point from v2 to v4 or whatever the latest is.

Paseto is already at the latest (1.3.1) as of this PR.

2021-12-06 18:47 UTC, patmaddox commented
Alright I've taken a closer look and it appears that the crypto issue only applies to v1 pasetos, and we use v2 pasetos.

2021-12-06 22:53 UTC, jc00ke requested changes

2021-12-06 22:53 UTC, jc00ke commented on lib/epi_contacts_web/views/search_view.ex
I don't think this function is even used anymore.

2021-12-06 22:53 UTC, jc00ke commented on lib/epi_contacts_web/views/search_view.ex
It's not tested, that's for sure, and...

```
  ➜ rg search_criteria
  lib/epi_contacts_web/views/search_view.ex
  8:  def search_criteria(first_name, last_name, street, city, state, zip_code, phone) do
```

2021-12-06 22:57 UTC, jc00ke commented on lib/epi_contacts_web/views/search_view.ex
Maybe we save that for a later PR with [mix_unused](https://github.com/hauleth/mix_unused).

2021-12-06 22:57 UTC, jc00ke approved these changes

2021-12-06 23:43 UTC, merged