replace skipped wallaby tests with working live tests
RatioPBC/epi-contacts pull request #23
Opened 2022-02-01 01:21 UTC by kenichi

2022-02-01 19:31 UTC, jc00ke requested changes

2022-02-01 19:31 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        |> then(fn i -> for _ <- 0..9, into: "", do: "#{i}" end)
Ooh, `then!` The first use I've seen in the wild! :partying_face:

Also, I'm surprised we're not already using [Faker](https://hexdocs.pm/faker/).

2022-02-01 19:31 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert view
Another candidate for extraction.

2022-02-01 19:31 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      element(view, "#delete-contact-1") |> render_click()
Hmm, you're removing `contact-1` here but asserting later that `contact-1` still exists and that `contact-3` does not. Am I missing something?

2022-02-01 19:31 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +             |> render() =~ "Thank you for helping us stop the spread of COVID-19."
`gettext` here?

2022-02-01 19:31 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        |> Timex.shift(days: 3)
Why a manual 3 days shift here? Does `PatientCase.isolation_end_date/1` not give you what you need?

2022-02-01 21:08 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      {:error, {:redirect, opts}} = live(conn, @path)
two things:

* I tried that in another place, but this assertion requires a `view` and we don't receive that in these cases.
* funny you should mention the query...
```
  1) test without locale set redirects to locale choice (EpiContactsWeb.Acceptance.QuestionnaireLiveTest)
     test/epi_contacts_web/acceptance/questionnaire_live_test.exs:41
     Assertion with == failed
     code:  assert URI.decode_query(query) == expected
     left:  %{"redirect_to" => "/start/ny-state-covid19/00000000-8434-4475-b111-bb3a902b398b?"}
     right: %{"redirect_to" => "/start/ny-state-covid19/00000000-8434-4475-b111-bb3a902b398b"}
     stacktrace:
       test/epi_contacts_web/acceptance/questionnaire_live_test.exs:50: (test)
```

2022-02-01 21:10 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert String.length(opts[:flash]) > 0
Hmm, not sure - if there's nothing put into flash, is it nil? or an encoded empty map? All in all, this might be a useless assertion, and I'm trying to figure out where it came from 🤔

2022-02-01 21:12 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +    test "accepts valid date of birth", %{conn: conn} do
there's many like this, happy to do so - I'm now unconvinced that splitting into multiple tests gets us anything, but open to ideas/suggestions.

2022-02-01 21:15 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      element(view, "#next-button") |> render_click()
I like the explicitness, but happy to extract if you feel it will read better.

2022-02-01 21:16 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert view
I was back and forth on extraction, but settled on only extracting large chunks that were used more than once. 3 lines didn't make the cut, but as above, happy to extract if it increases readability (from the old wallaby tests where everything was an extracted function, I'm feeling a bit like it wont... 🤷🏽‍♂️ )

2022-02-01 21:18 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      element(view, "#delete-contact-1") |> render_click()
I'm _clicking the delete contact button_ and liveview is removing the actual page elements. After adding other contacts, the element ids are reused. Note the different values.

2022-02-01 21:21 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +             |> render() =~ "Thank you for helping us stop the spread of COVID-19."
Note that we set "en" locale in the session during setup, but I'd be happy to refactor these to use translated strings. Mostly, I refactored from Wallaby to LiveView assertions directly, see: https://github.com/RatioPBC/epi-contacts/blob/main/test/support/assertions/confirmation.ex#L9

2022-02-01 21:27 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        |> Timex.shift(days: 3)
Ah, I'm not sure - pulled straight over from here: https://github.com/RatioPBC/epi-contacts/blob/main/test/epi_contacts_web/acceptance/questionnaire_test.exs#L273

I note `@isolation_span 5` so this might need other fixing to use.

2022-02-01 21:34 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  @date_tested ~D[2020-11-01]
In some places, I naively changed test values to get things passing, with the caveat that we'd go over them in light of changes since the Wallaby tests were skipped. Here's the first:

```elixir
@date_tested ~D[2020-05-13]
```

https://github.com/RatioPBC/epi-contacts/blob/main/test/epi_contacts_web/acceptance/questionnaire_test.exs#L25

2022-02-01 21:35 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  @non_symptomatic_end_date @date_tested |> Timex.shift(days: 3)
Here's another:

```elixir
@non_symptomatic_end_date @date_tested |> Timex.shift(days: 10)
```

https://github.com/RatioPBC/epi-contacts/blob/main/test/epi_contacts_web/acceptance/questionnaire_test.exs#L34

2022-02-01 21:43 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      {:error, {:redirect, opts}} = live(conn, @path)
ha and hmmm - from concourse

```
  1) test without locale set redirects to locale choice (EpiContactsWeb.Acceptance.QuestionnaireLiveTest)
     test/epi_contacts_web/acceptance/questionnaire_live_test.exs:41
     ** (FunctionClauseError) no function clause matching in String.length/1

     The following arguments were given to String.length/1:
     
         # 1
         %{}
     
     Attempted function clauses (showing 1 out of 1):
     
         def length(string) when is_binary(string)
     
     code: assert String.length(opts[:flash]) > 0
     stacktrace:
       (elixir 1.13.2) lib/string.ex:1968: String.length/1
       test/epi_contacts_web/acceptance/questionnaire_live_test.exs:44: (test)
```

2022-02-01 21:44 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert String.length(opts[:flash]) > 0
hmmm, from concourse (I don't get this locally)

```
  1) test without locale set redirects to locale choice (EpiContactsWeb.Acceptance.QuestionnaireLiveTest)
     test/epi_contacts_web/acceptance/questionnaire_live_test.exs:41
     ** (FunctionClauseError) no function clause matching in String.length/1

     The following arguments were given to String.length/1:
     
         # 1
         %{}
     
     Attempted function clauses (showing 1 out of 1):
     
         def length(string) when is_binary(string)
     
     code: assert String.length(opts[:flash]) > 0
     stacktrace:
       (elixir 1.13.2) lib/string.ex:1968: String.length/1
       test/epi_contacts_web/acceptance/questionnaire_live_test.exs:44: (test)
```

2022-02-01 22:44 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert String.length(opts[:flash]) > 0
Ah yeah, so `flash` itself must be a `Map`? I think so, because `flash[:error]` and its friends should be real things.

What's the local (your machine) value of `opts[:flash]`?

2022-02-01 22:45 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      {:error, {:redirect, opts}} = live(conn, @path)
Ah, you're right, good call on the `view` argument.

2022-02-01 22:47 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +    test "accepts valid date of birth", %{conn: conn} do
I don't mind small, focused tests. You _could_ probably get the `view` into the corresponding states w/o going through in order, but that would require more work than is necessary. I think focused tests when there are multiple scenarios in a given state is the right approach.

2022-02-01 22:48 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      element(view, "#next-button") |> render_click()
If this were only used once or twice, then having it be explicit would be fine, but it's used a lot, so may as well have a `render_click_next/1` function.

2022-02-01 22:49 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      element(view, "#delete-contact-1") |> render_click()
Ah, I missed that.

2022-02-01 22:50 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +             |> render() =~ "Thank you for helping us stop the spread of COVID-19."
On this first pass leaving the hard-coded string is fine, but in the future I'd consider using `gettext`.

2022-02-01 22:55 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert String.length(opts[:flash]) > 0
```diff
   describe "without locale set" do
     test "redirects to locale choice", %{conn: conn} do
-      assert {:error, {:redirect, %{to: to}}} = live(conn, @path)
+      assert {:error, {:redirect, %{flash: flash, to: to}}} = live(conn, @path)
+      IO.inspect(flash)
 ```

`SFMyNTY.g2gDdAAAAABuBgBcn363fgFiAAFRgA.Px5lqc4lS1uotA2H99fS43kQmyz0GSKesNwO8gReU2E`

🤷🏽‍♂️

2022-02-01 22:59 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        "Now, you&#39;ll be asked to add contacts you&#39;ve seen from"
That was another change made naively to get passing - original:

```elixir
session |> assert_has(css("h2", text: "Now, you'll be asked to add contacts you've seen from"))
```

https://github.com/RatioPBC/epi-contacts/blob/main/test/support/assertions/prep.ex#L9

2022-02-01 23:20 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  describe "when initial GET of data from CommCare does not have a test result" do
N.B. I've translated, but skipped this test - looking at `QuestionnaireLive.mount/3`, it doesn't seem like this is a case to be handled anymore. Am I missing anything?

2022-02-01 23:25 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert String.length(opts[:flash]) > 0
I've removed any flash checks here, since the locale plug is not setting any.

2022-02-01 23:27 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        "Now, you&#39;ll be asked to add contacts you&#39;ve seen from"
https://github.com/RatioPBC/epi-contacts/pull/23#discussion_r797114192

gettext next time/future

2022-02-01 23:29 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert view
[this](https://github.com/RatioPBC/epi-contacts/pull/23#discussion_r797114192) is the only other occurrence. extract?

2022-02-01 23:39 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  describe "when initial GET of data from CommCare does not have a test result" do
No, because this should get caught in the `EpiContactsWeb.Plugs.CommcareInfoLoader` plug.

2022-02-01 23:42 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +      assert view
More the `assert view |> element(selector) |> render()`.

2022-02-01 23:44 UTC, jc00ke commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        |> Timex.shift(days: 3)
We've had a lot of back-and-forth with DOH on the isolation span over the last few months, so I'd prefer to use existing machinery where possible so we don't accidentally introduce a regression.

2022-02-02 20:30 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  describe "when initial GET of data from CommCare does not have a test result" do
Hmmm, it seems to make it through that plug successfully - there's a case_id and domain, but apparently not a test result in the [data](https://github.com/RatioPBC/epi-contacts/blob/main/test/fixtures/commcare/case-without-test-results.json)?

2022-02-02 22:12 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +  describe "when initial GET of data from CommCare does not have a test result" do
discussion resulted in removal of this test.

2022-02-02 22:13 UTC, kenichi commented on test/epi_contacts_web/acceptance/questionnaire_live_test.exs
> +        |> Timex.shift(days: 3)
switched to `PageView.formatted_release_from_isolation_date/2`

2022-02-03 00:41 UTC, jc00ke approved these changes

2022-02-03 18:55 UTC, merged